NEWS_API_KEY = "pub_ea6292c128e7496da2492cf0de092565"
TWITTER_BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAALK68AEAAAAAXOh2DgAqmdOM%2FbLMZMGUh%2F2I9mI%3DVGBgeeoqzC5ceMb2crLBUjLAML2I1XEWtimslEGQjF5lOMhuRE"
GEMINI_API_KEY = "AIzaSyD5ILLWZvihbrDnND7LplP7JJ1kTFyXEa0"