GOOGLE_API_KEY = " AIzaSyDtO5OUMSDdJfP1QUscxvfJ8TzXPMRkS3k "           
CX_HK = "50e71848a8b0a4d9b"          
CX_WORLD = "a30d476fb987c4749"                    
NEWSDATA_API_KEY = "pub_ea6292c128e7496da2492cf0de092565"

